name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
        submodules: recursive
    - run: sudo apt-get update -qq
    - run: sudo apt-get install -qq -y --no-install-recommends autoconf automake libtool
    - run: make -j $(nproc) test
